//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenturaITC.DSMS.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesFields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesFields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VenturaITC.DSMS.App_GlobalResources.ResourcesFields", typeof(ResourcesFields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grau Académico.
        /// </summary>
        public static string AcademicLevel {
            get {
                return ResourceManager.GetString("AcademicLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string AcademicLevelRequired {
            get {
                return ResourceManager.GetString("AcademicLevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor a Pagar.
        /// </summary>
        public static string AmountToPay {
            get {
                return ResourceManager.GetString("AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string AmountToPayRequired {
            get {
                return ResourceManager.GetString("AmountToPayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Voltar a Lista.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string BirthdateRequired {
            get {
                return ResourceManager.GetString("BirthdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string CategoryRequired {
            get {
                return ResourceManager.GetString("CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de Celular.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Celular (Principal).
        /// </summary>
        public static string CellPhone1 {
            get {
                return ResourceManager.GetString("CellPhone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string CellPhone1Required {
            get {
                return ResourceManager.GetString("CellPhone1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Celular (Alternativo).
        /// </summary>
        public static string CellPhone2 {
            get {
                return ResourceManager.GetString("CellPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  inválido! Exemplo de número válido: 821234567..
        /// </summary>
        public static string CellPhoneMalformed {
            get {
                return ResourceManager.GetString("CellPhoneMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string CellPhoneRequired {
            get {
                return ResourceManager.GetString("CellPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Novo.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo Criminal.
        /// </summary>
        public static string CriminalRecordCertificate {
            get {
                return ResourceManager.GetString("CriminalRecordCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que pretende eliminar o registo?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitado.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Seleccionar-.
        /// </summary>
        public static string DropdownOptionLabel {
            get {
                return ResourceManager.GetString("DropdownOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Inscrição.
        /// </summary>
        public static string EnrollmentDate {
            get {
                return ResourceManager.GetString("EnrollmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomde do Pai.
        /// </summary>
        public static string FathersName {
            get {
                return ResourceManager.GetString("FathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string FathersNameRequired {
            get {
                return ResourceManager.GetString("FathersNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} longo. Deverá ter no máximo {1} caracteres..
        /// </summary>
        public static string FieldLong {
            get {
                return ResourceManager.GetString("FieldLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro Nome.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Inicial.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cópia de BI.
        /// </summary>
        public static string IDCopy {
            get {
                return ResourceManager.GetString("IDCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Expiração.
        /// </summary>
        public static string IDExpiryDate {
            get {
                return ResourceManager.GetString("IDExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string IDExpiryDateRequired {
            get {
                return ResourceManager.GetString("IDExpiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Emissão.
        /// </summary>
        public static string IDIssuanceDate {
            get {
                return ResourceManager.GetString("IDIssuanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string IDIssuanceDateRequired {
            get {
                return ResourceManager.GetString("IDIssuanceDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local de Emissão.
        /// </summary>
        public static string IDIssuancePlace {
            get {
                return ResourceManager.GetString("IDIssuancePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string IDIssuancePlaceRequired {
            get {
                return ResourceManager.GetString("IDIssuancePlaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de BI.
        /// </summary>
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválido!.
        /// </summary>
        public static string IDNumberMalformed {
            get {
                return ResourceManager.GetString("IDNumberMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string IDNumberRequired {
            get {
                return ResourceManager.GetString("IDNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profissão.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Língua.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Login.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Nome.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últ.  Alteração Senha.
        /// </summary>
        public static string LastPasswordChange {
            get {
                return ResourceManager.GetString("LastPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado da Carta.
        /// </summary>
        public static string LicenseStatus {
            get {
                return ResourceManager.GetString("LicenseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string LicenseStatusRequired {
            get {
                return ResourceManager.GetString("LicenseStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueiado.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logado.
        /// </summary>
        public static string Logged {
            get {
                return ResourceManager.GetString("Logged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativas Login.
        /// </summary>
        public static string LoginAttempts {
            get {
                return ResourceManager.GetString("LoginAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string MaritalStatusRequired {
            get {
                return ResourceManager.GetString("MaritalStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atestado Médico.
        /// </summary>
        public static string MedicalCertificate {
            get {
                return ResourceManager.GetString("MedicalCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaração de Serviço Militar.
        /// </summary>
        public static string MilitaryServiceStatement {
            get {
                return ResourceManager.GetString("MilitaryServiceStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Mínimo.
        /// </summary>
        public static string MinimumAmount {
            get {
                return ResourceManager.GetString("MinimumAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Mãe.
        /// </summary>
        public static string MothersName {
            get {
                return ResourceManager.GetString("MothersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string MothersNameRequired {
            get {
                return ResourceManager.GetString("MothersNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve Alterar Senha.
        /// </summary>
        public static string MustChangePassword {
            get {
                return ResourceManager.GetString("MustChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mal formado..
        /// </summary>
        public static string NameMalformed {
            get {
                return ResourceManager.GetString("NameMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Senha.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string PasswordConfirmRequired {
            get {
                return ResourceManager.GetString("PasswordConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida! Deverá conter pelo menos uma letra maíuscula, uma minúscula, um dígito e com tamanho entre 8 e 15 caracteres..
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicialização de Senha.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Pagamento.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string PaymentTypeRequired {
            get {
                return ResourceManager.GetString("PaymentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato inválido! Formato permitido: pdf..
        /// </summary>
        public static string PDFInvalidFormat {
            get {
                return ResourceManager.GetString("PDFInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  inválido! Exemplo de número válido: 21654321.
        /// </summary>
        public static string PhoneMalformed {
            get {
                return ResourceManager.GetString("PhoneMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de Telefone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotografia.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato inválido! Formatos permitidos: jpg, jpeg e png..
        /// </summary>
        public static string PictureInvalidFormat {
            get {
                return ResourceManager.GetString("PictureInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturalidade.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string PlaceOfBirthRequired {
            get {
                return ResourceManager.GetString("PlaceOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Província.
        /// </summary>
        public static string ProvinceOfBirth {
            get {
                return ResourceManager.GetString("ProvinceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string ProvinceOfBirthRequired {
            get {
                return ResourceManager.GetString("ProvinceOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº do Recibo.
        /// </summary>
        public static string ReceiptNumber {
            get {
                return ResourceManager.GetString("ReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string ReceiptNumberRequired {
            get {
                return ResourceManager.GetString("ReceiptNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Registo.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador Registo.
        /// </summary>
        public static string RegistrationUser {
            get {
                return ResourceManager.GetString("RegistrationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo de Aluno.
        /// </summary>
        public static string StudentCreate {
            get {
                return ResourceManager.GetString("StudentCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string StudentNumber {
            get {
                return ResourceManager.GetString("StudentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string StudentNumberRequired {
            get {
                return ResourceManager.GetString("StudentNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string StudentType {
            get {
                return ResourceManager.GetString("StudentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string StudentTypeRequired {
            get {
                return ResourceManager.GetString("StudentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Utilizador.
        /// </summary>
        public static string UserCreate {
            get {
                return ResourceManager.GetString("UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Utilizador.
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Utilizador.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Utilizadores.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReiniciarSenha.
        /// </summary>
        public static string UserPasswordReset {
            get {
                return ResourceManager.GetString("UserPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string UserRoleRequired {
            get {
                return ResourceManager.GetString("UserRoleRequired", resourceCulture);
            }
        }
    }
}
