CREATE TABLE [dbo].[student] (
    [number]               INT           IDENTITY (100, 1) NOT NULL,
    [student_type_id]      INT           NOT NULL,
    [full_name]            VARCHAR (255) NOT NULL,
    [first_name]           VARCHAR (50)  NOT NULL,
    [last_name]            VARCHAR (50)  NOT NULL,
    [birth_date]           DATE          NOT NULL,
    [marital_status_id]    INT           NOT NULL,
    [gender_id]            INT           NOT NULL,
    [place_of_birth]       VARCHAR (50)  NOT NULL,
    [province_of_birth_id] INT           NOT NULL,
    [fathers_name]         VARCHAR (255) NOT NULL,
    [mothers_name]         VARCHAR (255) NOT NULL,
    [address]              VARCHAR (255) NOT NULL,
    [id_number]            VARCHAR (50)  NOT NULL,
    [id_issuance_place]    INT           NOT NULL,
    [id_issuance_date]     DATE          NOT NULL,
    [id_expiry_date]       DATE          NOT NULL,
    [academic_level_id]    INT           NOT NULL,
    [job_title]            VARCHAR (100) NULL,
    [phone_number]         VARCHAR (50)  NOT NULL,
    [cell_phone1]          VARCHAR (50)  NOT NULL,
    [cell_phone2]          VARCHAR (50)  NULL,
    [email]                VARCHAR (255) NULL,
    [status_id]            INT           NOT NULL,
    CONSTRAINT [PK_Aluno] PRIMARY KEY CLUSTERED ([number] ASC),
    CONSTRAINT [FK_student_academic_level] FOREIGN KEY ([academic_level_id]) REFERENCES [dbo].[academic_level] ([id]),
    CONSTRAINT [FK_student_gender] FOREIGN KEY ([gender_id]) REFERENCES [dbo].[gender] ([id]),
    CONSTRAINT [FK_student_marital_status] FOREIGN KEY ([marital_status_id]) REFERENCES [dbo].[marital_status] ([id]),
    CONSTRAINT [FK_student_province] FOREIGN KEY ([province_of_birth_id]) REFERENCES [dbo].[province] ([id]),
    CONSTRAINT [FK_student_province1] FOREIGN KEY ([id_issuance_place]) REFERENCES [dbo].[province] ([id]),
    CONSTRAINT [FK_student_status] FOREIGN KEY ([status_id]) REFERENCES [dbo].[status] ([id]),
    CONSTRAINT [FK_student_student_type] FOREIGN KEY ([student_type_id]) REFERENCES [dbo].[student_type] ([id])
);

